### ISSUE TITLE
Any updates on this?

### ISSUE THREAD

**Issue by RaeesBhatti** [kastermester/graphql-hack#1]
This is a lovely project and I would love to see it made useable. I have project where I intend to use GraphQL and seems like you already have a good start. Is there any estimate when you'll be able to work on this again.
I'll be able to contribute if you're interested.

**Comment by kastermester** [comment]
Sorry, for some reason my github notification seems to have gotten lost somewhere :)

I have been quite swamped on both my professional and personal life - so haven't had the time to work on this lately, but I do intend finishing the implementation, but unfortunately I don't really have any estimates on when this will be.

I am more than happy to accept any contributions, in any forms. May it be bug reports, docs, PRs with the missing functionality, etc. Feel free to contact me in any forms you see fit :) I hang out on the reactiflux discord when at work (same handle as here) - in case you want to make contact in more real time form :)

FYI, I started working on this for two main reasons:
1. I would love to get a more deep knowledge on the GraphQL server implementation.
2. Once my place of work switches our PHP engine out with HHVM, I expect us to look at, and switch our custom RESTish endpoints out with a GraphQL backend - for which we'd need a Hack backend supporting truly asynchronous execution. So in the truly horrible case, I would be able to work on this at work when this time comes, however - there's no real timeline on this right now - my hope is this year / early next year. Sadly though I am not the one making the calls for this.

Lovely to see interest from others than myself! :)

EDIT: I realise I did not specify any timezone information. I'm based in Europe/Denmark.

**Comment by kastermester** [comment]
@raeesiqbal While I realise I myself was slow to respond, I'm still looking forward to hear from you :)

I have _slowly_ started the work on porting `graphql/type`. However I have run into some annoyances given that the tests in that module heavily depends on the rest of the execution infrastructure.

**Comment by raeesiqbal** [comment]
I'm really sorry about this. I had planned to reply to this properly but completely forgot about this. My apologies.

The project I'm working on is still in the initial phase, so, we haven't implemented the web exposed API yet. Which is where I intend to use GraphQL instead of REST with JSON. Facebook had promised to open source their Hack version of GraphQL implementation later this year. But they usually don't make good on promises like these.
Now that you've started working on this, I'll start working on the API too. Lets get this project in good working position a lot earlier than they release their version.

**Comment by raeesiqbal** [comment]
I'm actually also waiting for the Docker for Windows Beta invite, because VirtualBox doesn't work in my build of the Windows 10 Pro. So, I might be a little late with PR but don't worry, I have it bookmarked now.

**Comment by kastermester** [comment]
Sounds good :)

I was kind of hoping that maybe you would be able to implement and test the `Visitor::visitInParallel` and `Visitor::visitWithTypeInfo` methods before I finish `graphql/types` module. From this point on we might be able to work on the execution and validation concurrently.

How does this sound to you?

If anyone else is keeping an eye on this and wants to help in, please comment on this issue.

Almost forgot: Please base all of your work off of graphql/graphql-js@a6bcc75d3c19ce31847cd77279a41fbc6ac032d2 when we're done porting, we can then work our way through the various commits since then.

**Comment by raeesiqbal** [comment]
Sounds great. I have Docker up and running today. Will start working on it tomorrow and will let you know.
